name: server
description: A chatroom server.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  logging: ^1.0.2
  path: ^1.8.0
  protobuf: ^2.0.1

dev_dependencies:
  lints: ^1.0.0
